// Generated by https://quicktype.io

class Imagen {
  //se declaran variables, piensa en python
  String copyright;
  String date;
  String explanation;
  String hdurl;
  String mediaType;
  String serviceVersion;
  String title;
  String url;

  Imagen({
    //constructor
    this.copyright,
    this.date,
    this.explanation,
    this.hdurl,
    this.mediaType,
    this.serviceVersion,
    this.title,
    this.url,
  });
  Imagen.fromJsonMap(Map<String, dynamic> deljson) {
    //metodo

    copyright = deljson['copyright'];
    date = deljson['date'];
    explanation = deljson['explanation'];
    hdurl = deljson['hdurl'];
    mediaType = deljson['media_type'];
    serviceVersion = deljson['service_version'];
    title = deljson['title'];
    url = deljson['url'];
  }
}
